### PR TITLE
remove weights for surveys other than participants

### LINKED ISSUE #40: `age.groups` variable in `contact.matrix()` not defined
From https://github.com/epiforecasts/socialmixr/pull/37:

It seems that the change in 7dcfca5fdb3046f6d13e3c32824f0ba0a7d08038 reveals a hidden bug. The `age.group` variable in `contact_matrix()` is actually never defined. data.table was quite happy with it being `NULL`, as set initially but now it's registered as an actual global variable, it doesn't work:

https://github.com/epiforecasts/socialmixr/blob/c83358240dc751602ec4fb30c5dc901590563707/R/contact_matrix.r#L550-L555

### PR DESCRIPTION
**Pull request by sbfnk**
Currently, weights are applied to both participants and contacts. However, it is not clear if weights for contacts make sense. They are not documented, not mentioned in the vignette, and at the very least would need an option to check if a user would want weights applied to contacts.

This PR removes weights for any survey but the participant survey. For the day of the week, for example, this means that weights can be applied to correct for an imbalanced representation in weekdays/weekends amongst when participant completed their survey, but no further weighting is applied to contacts based on the day on which the contact occurred.

If there is ever a use case where weights are to be applied to contacts, this could and should be re-implemented in a clearer way. For now, I think they are better removed.

Fixes #40 and reverts #44.

The diff highlights quite a few changes but most of them are changed indentation because `for` statements have been removed.

### CODE REVIEW

**Comment by sbfnk** [comment]
@lwillem feel free to have a look given that you worked a lot on the implementation of weights.

**Comment by lwillem** [comment]
Sorry for the inconvenience on this. I'll have a look at it today

**Comment by Bisaloo** [comment]
Link to diff without indent changes: https://github.com/epiforecasts/socialmixr/pull/46/files?w=1

File: R/contact_matrix.r [hunk 1]
```diff
@@ -433,30 +431,26 @@ contact_matrix <- function(survey, countries = c(), survey.pop, age.limits, filt
...
-        survey[[table]][, sum_weight := NULL]
-        found.dayofweek <- TRUE
+      survey$participants[, sum_weight := NULL]
+      found.dayofweek <- TRUE
 
-        # add boolean for "weekday"
-        survey[[table]][, is.weekday := dayofweek %in% 1:5]
-      }
+      # add boolean for "weekday"
+      survey$participants[, is.weekday := dayofweek %in% 1:5]
```
Comment (Bisaloo) [inline R/contact_matrix.r:453]: For another PR (let's keep this one focused): it would be slightly clearer if we created the `is.weekday` column earlier and used it on L440, 445 & 447.

**Review by Bisaloo — APPROVED** [review]

**Comment by lwillem** [comment]
I fully agree that the weights for the contacts are not used at this stage, and are likely to cause issues. However, "age.group" is still needed in survey$contacts to get the contact rates.

**Comment by lwillem** [comment]
I guess that the assignment of age.groups in survey$contacts should move up. This does not fully solve the issue with "missing.contact.age == samle")

Screenshot 2022-09-01 at 17 02 08
Screenshot 2022-09-01 at 17 02 15

**Comment by sbfnk** [comment]
> I guess that the assignment of age.groups in survey$contacts should move up. This does not fully solve the issue with "missing.contact.age == samle")

That is a very good point but, I think, a different issue. Will merge this and open another Issue for the problem that you have identified.

**Comment by sbfnk** [comment]
Scratch that, sorry, I think the code is correct as intended (if poorly documented). If some contact ages are NA they are sampled from all the ages of contacts of *participants* of the same age group (i.e. assuming people of the same age group are similar).

**Comment by lwillem** [comment]
yes, indeed, the age.group of the participant is used here. sorry
