### PR TITLE
Implementing fixes for lintr

### LINKED ISSUE #185: address lintr requests
As discussed in https://github.com/epiforecasts/socialmixr/pull/182#issuecomment-3153852592 we should make a separate PR to address the problems found by lintr

### PR DESCRIPTION
**Pull request by njtierney**
Resolves #185 

- skip some lines e.g., `"i" = ` in `cli`, and assigning inside tests for snapshot tests as we just want the warning
- many various other fixes from suggestions from lintr :)

## Summary by CodeRabbit

* **Style**
  * Improved code readability by renaming variables for clarity and updating function return styles to use implicit returns.
  * Added or adjusted linter suppression comments to reduce unnecessary warnings in code and tests.
  * Updated library loading calls to use unquoted package names for consistency.

* **Documentation**
  * Enhanced vignettes by replacing print statements with cat for cleaner output display.

* **Tests**
  * Added a new test snapshot for warning conditions in contact matrix calculations.
  * Updated linter suppression comments in test files for improved code quality.

### CODE REVIEW

File: tests/testthat/test-matrix.r [hunk 1]
```diff
@@ -199,7 +199,7 @@ test_that("warning is thrown if population needed but no 'year' column present",
 
 test_that("warning is thrown if day of week is asked to be weighed but not present", {
   expect_snapshot(
-    tmp <- contact_matrix(survey = polymod3, weigh.dayofweek = TRUE),
+    tmp <- contact_matrix(survey = polymod3, weigh.dayofweek = TRUE) #nolint
```
Comment (sbfnk) [inline tests/testthat/test-matrix.r:202]: do we actually need the assignment here? 
```suggestion
    tmp <- contact_matrix(survey = polymod3, weigh.dayofweek = TRUE) # nolint
```

File: R/contact_matrix.R [hunk 2]
```diff
@@ -783,7 +794,7 @@ contact_matrix <- function(
         c(
           "{.code symmetric = TRUE} does not work with missing data; will \\
           not make matrix symmetric.",
-          "i" = "{warning.suggestion}"
+          "i" = "{warning.suggestion}" # nolint
```
Comment (sbfnk) [inline R/contact_matrix.R:797]:
```suggestion
          # nolint start
          "i" = "{warning.suggestion}"
          # nolint end
```
unless there is a reason for the different format here?

File: R/lists.R [hunk 3]
```diff
@@ -99,5 +99,6 @@ wpp_countries <- function() {
       "country.name"
     ))
   found_countries <- found_countries[!is.na(found_countries)]
```
Comment (sbfnk) [inline R/lists.R:101]:
```suggestion
  found_countries[!is.na(found_countries)]
```

File: R/lists.R [hunk 4]
```diff
@@ -99,5 +99,6 @@ wpp_countries <- function() {
...
-  return(found_countries)
+
+  found_countries
```
Comment (sbfnk) [inline R/lists.R:103]:
```suggestion
```

File: tests/testthat/test-matrix.r [hunk 5]
```diff
@@ -288,13 +292,14 @@ test_that("nonsensical operations are warned about", {
 })
 
 test_that("warning is thrown if it is assumed that the survey is representative", {
-  expect_warning(
-    contact_matrix(
+  expect_snapshot(
+    # nolint start
```
Comment (sbfnk) [inline tests/testthat/test-matrix.r:296]: do we need this because `tmp` is not used and, if yes, do we even need it?

File: R/cite.R [hunk 6]
```diff
@@ -25,5 +25,5 @@ get_citation <- function(x) {
 
   bref <- do.call(bibentry, ref)
```
Comment (sbfnk) [inline R/cite.R:27]:
```suggestion
  do.call(bibentry, ref)
```

File: R/cite.R [hunk 7]
```diff
@@ -25,5 +25,5 @@ get_citation <- function(x) {
...
 
-  return(bref)
+  bref
```
Comment (sbfnk) [inline R/cite.R:28]:
```suggestion
```

**Review by sbfnk — APPROVED** [review]
Great! Just a few minor suggestions.

File: tests/testthat/test-matrix.r (hunk 5 above)
Comment (njtierney) [reply tests/testthat/test-matrix.r:296]: tmp isn't used, it's a bit of a workaround to avoid the snapshot capturing the entire output of the table, but we only want the warning.

We want to capture the warning message, and it seems that changing over to the `cli` warning messages slightly break the regex that `expect_warning` was testing for. 

Ideally we would use `expect_snapshot_warning` but it seems it is in a questioning lifecycle (https://testthat.r-lib.org/reference/expect_snapshot_output.html), so if I use `expect_snapshot()` on the output, it captures the whole table. We could get around this by using `expect_snapshot_warning()` and then eventually if the testthat deprecates the function we can deal with it then. I have asked them about this here: https://github.com/r-lib/testthat/issues/2182.

File: R/lists.R (hunk 3 above)
Comment (njtierney) [reply R/lists.R:101]: Thanks for this! I'm not a regular data.table user so I sometimes get tripped up on the copy-by-reference approach

File: tests/testthat/test-matrix.r (hunk 5 above)
Comment (njtierney) [reply tests/testthat/test-matrix.r:296]: Overall I think it is cleaner to just use `expect_snapshot_warning()`, so I'll do that, I think.

Comment (njtierney) [reply tests/testthat/test-matrix.r]: It might be worthwhile thinking about using snapshot testing in other parts of socialmixr however, as it is a bit more complete than using regexes. I'll post an issue about it.

File: tests/testthat/test-matrix.r (hunk 1 above)
Comment (njtierney) [reply tests/testthat/test-matrix.r]: See below discussion about expect_snapshot_warning(), which resolves this :)

File: tests/testthat/test-matrix.r (hunk 5 above)
Comment (njtierney) [reply tests/testthat/test-matrix.r]: Using expect_snapshot_warning() resolves this :)
